### ISSUE TITLE
Request to add my configuration

### ISSUE THREAD

**Issue by Zabooby** [stax76/awesome-mpv#1]
I recently came across this great resource and noticed you have a User Configuration [section](https://github.com/stax76/awesome-mpv#user-configuration), I was wondering if you would mind adding my [config ](https://github.com/Zabooby/mpv-config) too. I have added elements from loads of other configs and have some [plans](https://github.com/users/Zabooby/projects/1) to improve it too. 

PS: Thanks for creating this awesome list!

**Comment by stax76** [comment]
I'm glad to add it.

**Comment by candrapersada** [comment]
can it be used on mpv.net without destroying mpv.net's input.conf?

**Comment by Zabooby** [comment]
> [Zabooby](https://github.com/Zabooby) can it be used on mpv.net without destroying mpv.net's input.conf?

[mpv.net](https://github.com/mpvnet-player/mpv.net#-mpvnet) is not just a gui for mpv, it's its own media player based on mpv. My entire config is basically built around [uosc](https://github.com/darsain/uosc) which is a gui so using mpv.net instead wouldn't work with my config by just copy and pasting my portable_config folder.

You could change some of the key bindings for some of my scripts to work with mpv.net. Also if you want, you can copy my [mpv.conf](https://github.com/Zabooby/mpv-config/blob/main/portable_config/mpv.conf) settings in the mpv.net menu. For shaders and scalers you could add them as profiles in your mpv.conf/input.conf. 

Other than that there isn't much I can help with. Is there any reason why you want to use mpv.net over uosc, uosc is much more configurable, but I understand that mpv.net can be much more newbie friendly?

**Comment by candrapersada** [comment]
![image](https://user-images.githubusercontent.com/36833664/210351027-1a05570e-05f2-4d0b-ab12-ddf4f2309a06.png)
![image](https://user-images.githubusercontent.com/36833664/210350521-30d6a679-51b8-41b0-a7de-c38ae93076b9.png)
