### ISSUE TITLE
An interesting configuration with browser integration

### ISSUE THREAD

**Issue by GunGunGun** [stax76/awesome-mpv#12]
Repo: https://github.com/tuilakhanh/mpv-config
By @tuilakhanh

It can integrate into Firefox seamlessly using this plugin, protocol_hook: https://github.com/FirefoxUniverse/FirefoxTweaksVN/tree/main/mpv/scripts

Allowing Firefox to natively open MPV without any kind of external software. Here's the result:
https://streamable.com/4s1gfi

**Comment by monarc99** [comment]
The mpv part is clear, but how do you integrate it into Firefox?

**Comment by stax76** [comment]
I've added it.

**Comment by GunGunGun** [comment]
> The mpv part is clear, but how do you integrate it into Firefox?

Read this guide:
https://github.com/mpv-player/mpv/discussions/14506
