### ISSUE TITLE
two new glsl shader - AniSD ArtCNN - Ani4K v2 ArtCNN

### ISSUE THREAD

**Issue by monarc99** [stax76/awesome-mpv#15]
Here are two new glsl shaders. Could be added to the list, but require a powerful GPU.

AniSD ArtCNN (GLSL Shader) -> https://slow.pics/c/1Ibz4w8J
Ani4K v2 ArtCNN (GLSL Shader) -> https://slow.pics/c/gqrp7CsC

Download: https://github.com/Sirosky/Upscale-Hub/releases

**Comment by stax76** [comment]
You can add them here:

https://github.com/mpv-player/mpv/wiki/User-Scripts

I monitor changes there and sync it every other month.
