### ISSUE TITLE
Audio/Video track info

### ISSUE THREAD

**Issue by bE7rwls** [stax76/awesome-mpv#4]
Hi, in mpv.net i can see bitrate info in tracks menu, what should i do to see the same in MPV?
![mpvnet](https://github.com/stax76/awesome-mpv/assets/67607468/b339cd0a-f8c1-47db-9ab2-4f253d4611be)
![mpv](https://github.com/stax76/awesome-mpv/assets/67607468/1a68ad6f-47a1-45a7-a256-f886b9c49e01)

**Comment by stax76** [comment]
I don't think mpv can give bitrates, in mpv.net this info comes from the mediainfo library.

**Comment by aicynide** [comment]
@stax76 mediainfo script for mpv?

**Comment by stax76** [comment]
There is one written by me, here:

https://github.com/stax76/mpv-scripts/blob/main/misc.lua
