### ISSUE TITLE
Gnome extensions

### ISSUE THREAD

**Issue by 07416** [stax76/awesome-mpv#6]
If you accept Gnome extensions, this can one can prevent the display from turning off (Gnome doesn't support the idle-inhibit protocol on Wayland) and disable the 'night light' when a mpv window is in focus: https://github.com/eonpatapon/gnome-shell-extension-caffeine

see the manual: https://mpv.io/manual/stable/#linux-desktop-issues

**Comment by 07416** [comment]
@stax76 Are you following the issues on this repo? My pull request was quickly accepted.

**Comment by stax76** [comment]
I've added it, thanks.
